name: google_geofence_helper
description: A Flutter package for interactive map geofencing with support for freeform polygon creation and editing
version: 0.0.1
homepage: https://github.com/yourusername/google_geofence_helper

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.3
  google_maps_flutter_web: ^0.5.4+3
  collection: ^1.17.2
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 